// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOtAsS7RvCp_KVo3yLxXfHRL_nRR01DU',
    appId: '1:46216843544:web:0bcfe7df03e9e0b6dace6d',
    messagingSenderId: '46216843544',
    projectId: 'yasin-tahlil-premium',
    authDomain: 'yasin-tahlil-premium.firebaseapp.com',
    storageBucket: 'yasin-tahlil-premium.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIH_YR3IttkKr3BFrCJx_IQTQsqU0Hgjg',
    appId: '1:46216843544:android:022c8b363c97872adace6d',
    messagingSenderId: '46216843544',
    projectId: 'yasin-tahlil-premium',
    storageBucket: 'yasin-tahlil-premium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDharpgb0nVUty3L4O3x6II4AwI5_6uMRQ',
    appId: '1:46216843544:ios:35401faba6c3b1dfdace6d',
    messagingSenderId: '46216843544',
    projectId: 'yasin-tahlil-premium',
    storageBucket: 'yasin-tahlil-premium.firebasestorage.app',
    iosBundleId: 'com.yusuf.yasinTahlil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDharpgb0nVUty3L4O3x6II4AwI5_6uMRQ',
    appId: '1:46216843544:ios:35401faba6c3b1dfdace6d',
    messagingSenderId: '46216843544',
    projectId: 'yasin-tahlil-premium',
    storageBucket: 'yasin-tahlil-premium.firebasestorage.app',
    iosBundleId: 'com.yusuf.yasinTahlil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOtAsS7RvCp_KVo3yLxXfHRL_nRR01DU',
    appId: '1:46216843544:web:ad68612bc031448fdace6d',
    messagingSenderId: '46216843544',
    projectId: 'yasin-tahlil-premium',
    authDomain: 'yasin-tahlil-premium.firebaseapp.com',
    storageBucket: 'yasin-tahlil-premium.firebasestorage.app',
  );
}
